[package]
name = "movie-db-sql-migration-script"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
tokio = { version = "1", features = ["full"] }
oracle = "0.5"
serde = { version = "1.0.215", features = ["derive"] }
rand = "0.8.5"
dotenv = "0.15"
